name: Run Analysis Notebook
on: [push]
jobs:
  run-analysis-notebook:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - uses: prefix-dev/setup-pixi@v0.9.3
        with:
          pixi-version: v0.59.0

          cache: true
      - run: pixi run jupyter execute analysis.ipynb
